---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[cop_ntp::default]
    attributes:
